apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: lifeconquest/lifeconquest-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/conf.d/
              readOnly: true
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-config
            items:
              - key: default.conf
                path: default.conf
