"""intermed

Revision ID: 545c74b85d6d
Revises: be855a237317
Create Date: 2025-01-07 11:24:46.076239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545c74b85d6d'
down_revision: Union[str, None] = 'be855a237317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clans', sa.Column('description', sa.String(), nullable=False))
    op.drop_constraint('passed_clan_war_participants_passed_clan_war_id_fkey', 'passed_clan_war_participants', type_='foreignkey')
    op.create_foreign_key(None, 'passed_clan_war_participants', 'passed_clan_wars', ['passed_clan_war_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('daily_task', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('occupied', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('d0', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d1', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d2', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d3', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d4', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d5', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('d6', sa.Integer(), nullable=False))
    op.drop_column('users', 'week_score')
    op.drop_column('users', 'skipped_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skipped_score', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('week_score', sa.VARCHAR(length=168), autoincrement=False, nullable=False))
    op.drop_column('users', 'd6')
    op.drop_column('users', 'd5')
    op.drop_column('users', 'd4')
    op.drop_column('users', 'd3')
    op.drop_column('users', 'd2')
    op.drop_column('users', 'd1')
    op.drop_column('users', 'd0')
    op.drop_column('users', 'occupied')
    op.drop_column('users', 'daily_task')
    op.drop_constraint(None, 'passed_clan_war_participants', type_='foreignkey')
    op.create_foreign_key('passed_clan_war_participants_passed_clan_war_id_fkey', 'passed_clan_war_participants', 'passed_clan_wars', ['passed_clan_war_id'], ['id'], ondelete='SET NULL')
    op.drop_column('clans', 'description')
    # ### end Alembic commands ###
