"""initial

Revision ID: be855a237317
Revises: 
Create Date: 2024-11-21 09:45:23.617417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be855a237317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('skipped_score', sa.SmallInteger(), nullable=False),
    sa.Column('week_score', sa.String(length=168), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('participate_division', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clans',
    sa.Column('clanname', sa.String(length=32), nullable=False),
    sa.Column('owner_membership_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('recruiting', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clanname'),
    sa.UniqueConstraint('owner_membership_id')
    )
    op.create_table('clan_memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_foreign_key(None, 'clans', 'clan_memberships', ['owner_membership_id'], ['id'], ondelete='CASCADE')
    op.create_table('divisions',
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passed_divisions',
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan_requests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'clan_id', name='user_clan_unique')
    )
    op.create_table('clan_war_invite',
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_id')
    )
    op.create_table('clan_wars',
    sa.Column('clan_1_id', sa.Integer(), nullable=False),
    sa.Column('clan_2_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_1_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clan_2_id'], ['clans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_1_id'),
    sa.UniqueConstraint('clan_2_id')
    )
    op.create_table('division_memberships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('duel_invites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('duels',
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_1_score', sa.SmallInteger(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.Column('user_2_score', sa.SmallInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_1_id'),
    sa.UniqueConstraint('user_2_id')
    )
    op.create_table('passed_clan_wars',
    sa.Column('clan_1_id', sa.Integer(), nullable=True),
    sa.Column('clan_2_id', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_1_id'], ['clans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clan_2_id'], ['clans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passed_division_memberships',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('passed_division_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['passed_division_id'], ['passed_divisions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passed_duels',
    sa.Column('user_1_id', sa.Integer(), nullable=True),
    sa.Column('user_1_score', sa.SmallInteger(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=True),
    sa.Column('user_2_score', sa.SmallInteger(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_1_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_2_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clan_war_participants',
    sa.Column('user_membership_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('clan_war_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clan_war_id'], ['clan_wars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_membership_id'], ['clan_memberships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_membership_id')
    )
    op.create_table('passed_clan_war_participants',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('passed_clan_war_id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['passed_clan_war_id'], ['passed_clan_wars.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passed_clan_war_participants')
    op.drop_table('clan_war_participants')
    op.drop_table('passed_duels')
    op.drop_table('passed_division_memberships')
    op.drop_table('passed_clan_wars')
    op.drop_table('duels')
    op.drop_table('duel_invites')
    op.drop_table('division_memberships')
    op.drop_table('clan_wars')
    op.drop_table('clan_war_invite')
    op.drop_table('clan_requests')
    op.drop_table('users')
    op.drop_table('passed_divisions')
    op.drop_table('divisions')
    op.drop_table('clans')
    op.drop_table('clan_memberships')
    # ### end Alembic commands ###
