from os import environ
from datetime import timedelta

POSTGRESQL_DATABASE = environ['POSTGRESQL_DATABASE']
POSTGRESQL_USERNAME = environ['POSTGRESQL_USERNAME']
POSTGRESQL_PASSWORD = environ['POSTGRESQL_PASSWORD']
POSTGRESQL_PORT_NUMBER = environ['POSTGRESQL_PORT_NUMBER']

POSTGRESQL_URL = f'postgresql+psycopg2://{POSTGRESQL_USERNAME}:{POSTGRESQL_PASSWORD}@db:{POSTGRESQL_PORT_NUMBER}/{POSTGRESQL_DATABASE}'

JWT_KEY = environ['JWT_KEY']
JWT_ALGORITHM = 'HS256'

DUEL_TIME_SPAN = timedelta(days=3)
CLAN_WAR_TIME_SPAN = timedelta(days=3)

CLAN_MAX_MEMBERS_COUNT = 10

CLAN_WAR_ABSOLUTE_SCORE_DELTA = 1000
CLAN_WAR_RELATIVE_SCORE_DELTA = 2

CLAN_WAR_AVERAGE_WEEK_SCORE_ABSOLUTE_DELTA = 1000

DUEL_THRESHOLD_SCORE = 250
DUEL_ABSOLUTE_SCORE_DELTA = 200
DUEL_RELATIVE_SCORE_DELTA = 2

DUEL_WEEK_SCORE_ABSOLUTE_DELTA = 150

DIVISION_THRESHOLD_SCORE = 250
DIVISION_MAX_PARTICIPANTS_COUNT = 50

TASK_MIN_MINUTES = 10
TASK_MAX_MINUTES = 120

DAILY_TASK_PENALTY = 30